name: OpenaiGPTLLM
model_id: Qwen/Qwen2.5-7B-Instruct
api_key: ${env| custom_openai_key, sk-tlktjijivftauscpmcknctcbrnziqmbuoqkfxjjwomnjbgsr}
endpoint: ${env| custom_openai_endpoint, https://api.siliconflow.cn/v1}
temperature: 0
vision: false