name: OpenaiGPTLLM
model_id: InternVL2_5-1B
api_key: ${env| custom_openai_key, c549be1a-2cba-40d7-a30b-39622789f190}
endpoint: ${env| custom_openai_endpoint, http://140.207.201.47:6235/v1}
temperature: 0
vision: true