name: OpenaiGPTLLM
model_id: /data23/qq/resources/Qwen/Qwen2.5-VL-3B-Instruct
api_key: ${env| custom_openai_key, c549be1a-2cba-40d7-a30b-39622789f190}
endpoint: ${env| custom_openai_endpoint, http://10.8.25.27:30002/v1}
temperature: 0
vision: true