name: OpenaiGPTLLM
model_id: gpt-4o-utdog
api_key: ${env| custom_openai_key, sk-2ju1fJ8hzN63oAva3tOiajUOyO756tqRt2XPD8N0yl2nqWL7}
endpoint: ${env| custom_openai_endpoint, http://10.8.17.22:3000/v1}
temperature: 0.5
response_format: text